owner: DiscordSRV
repo: Status

sites:
  - name: Downloads
    url: https://get.discordsrv.com
  - name: Documentation
    url: https://docs.discordsrv.com
  - name: Bin
    url: https://bin.scarsz.me
  - name: Config redirections
    url: https://config.discordsrv.com
  - name: Heads
    url: https://heads.discordsrv.com

status-website:
  cname: status.discordsrv.com
  logoUrl: https://lol.scarsz.me/AiKvTS/Logo-filled-stroke.png
  theme: night
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
